### ISSUE TITLE
Refactoring nötig

### ISSUE THREAD

**Issue by aggsol** [Stitch7/mservice#1]
Damit man ordentlich mithelfen kann, ist es besser alles Aspekte in eigene Dateien zu extrahieren. Mit einer riesen Source-Datei mergen wir und ja blöde :-)

**Comment by Stitch7** [comment]
So nach langer, langer Zeit kann ich das Ding hier glaub ich schließen.
Bin kein JavaScript Pro, aber immer für Verbesserungsvorschläge offen ;)

**Comment by aggsol** [comment]
Ich nehme mal an, du arbeitest wieder dran? Denn eine REST API für das Forum ist einfach nötig. Arbeitest du an etwas bestimmten?

**Comment by Stitch7** [comment]
Siehe aktuellen Stand im master, habe das ganze mal etwas überarbeitet. Diese Version wird mit der neuen Version der iOS App live gehen.
