### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by aggsol** [Stitch7/mservice#5]
Das Forum zeigt auch noch an wieviel und wer gerade online ist. Also etwa:

* `mservice/users/online`
* `mservice/users/count`

**Comment by Stitch7** [comment]
Moin, hatte da sogar noch einen Codeschnipsel rumfliegen, mal spontan in die aktuelle Architektur integriert, gepushed und deployed:
[https://nerds.berlin/mservice/users/online](https://nerds.berlin/mservice/users/online)
